Añadir imagen de acciones disponibles para partner y non-partner
lacchain/eosio.lacchain.net pull request #109
Opened 2021-07-01 16:38 UTC by AngeloCG97

## Añadir imagen de acciones disponibles para partner y non-partner 

#107

## ¿Qué tiene este PR?
1. Add images in crear-cuenta-entidad.md

2021-07-01 17:52 UTC, xavier506 requested changes
tenemos esta otra pagina , posiblemente podemos enlazar a esta pagina desde cada guia

https://eosio.lacchain.net/docs/herramientas/gobernanza-red

2021-07-01 20:16 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> +[Consulte sobre la lista de acciones disponibles para los partners](../herramientas/gobernanza-red)
podriamos indicar que el usuario debe ingresar los datos sobre su entidad usando la herramienta de gobernanza como un paso en el proceso de registro,  en otras palabras podemos incluir un poco mas de texto explicando que se debe de completar este paso junto con. el enlace

2021-07-01 20:16 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> +[Consulte sobre la lista de acciones disponibles para los partners](../herramientas/gobernanza-red)
@AngeloCG97

2021-07-01 20:25 UTC, AngeloCG97 commented on docs/guias/crear-cuenta-entidad.md
> +[Consulte sobre la lista de acciones disponibles para los partners](../herramientas/gobernanza-red)
ok de acuerdo.

2021-07-04 22:49 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> +3. Añada los datos sobre su entidad non-partner utilizando las herramientas de [gobernanza de la red](../herramientas/gobernanza-red).
@AngeloCG97  que te parece si incluimos ambos enlaces asi: 


 utilizando las [herramientas](
). de [gobernanza de la red](../herramientas/gobernanza-red)

2021-07-04 22:50 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> +3. Añada los datos sobre su entidad non-partner utilizando las herramientas de [gobernanza de la red](../herramientas/gobernanza-red).
idealmente incluimos ambos enlaces en este texto de alguna manera

2021-07-05 16:22 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> -4. Siga las [instrucciones](./instalacion-nodos) para implementar un nodo de escritor y envíenos la información del nodo que obtiene al final del proceso a info@lacchain.net para autorizar su nodo.
@AngeloCG97  no eliminar este paso y cambiar el enlace por https://lacchain.eosio.online/management

2021-07-05 16:23 UTC, xavier506 commented on docs/guias/crear-cuenta-entidad.md
> +Añada los datos sobre su entidad **partner** o **no partner** utilizando las herramientas de [gobernanza de la red](../herramientas/gobernanza-red).
Conozca más sobre la  herramientas de [gobernanza de la red](../herramientas/gobernanza-red) para administrar su cuenta en LACChain.

2021-07-05 19:43 UTC, xavier506 approved these changes
LGTM

2021-07-05 19:43 UTC, merged