Guía sobre cómo preparar transacciones en LACCHAIN EOSIO
lacchain/eosio.lacchain.net pull request #110
Opened 2021-07-02 15:06 UTC by AngeloCG97

## Guía sobre cómo preparar transacciones en LACCHAIN EOSIO 

#19

## ¿Qué tiene este PR?
1. Create prepare transacction tutorial

2021-07-02 15:40 UTC, xavier506 commented on i18n/en/docusaurus-plugin-content-docs/current/guias/transacciones.md
> +To execute actions in a LACChain EOSIO contract it is necessary to prepare and execute transactions, here you can observe some considerations about this process.
To execute transaction on LACChain EOSIO it is necessary to include at least two actions for each transaction.

The smart contract action you would like to execute and and  `writer::run` action which includes the authorization of the writer node who will provide the necessary network resources to execute the transaction.

 here is an example transaction:

2021-07-02 15:41 UTC, xavier506 commented on i18n/en/docusaurus-plugin-content-docs/current/guias/transacciones.md
> +To execute actions in a LACChain EOSIO contract it is necessary to prepare and execute transactions, here you can observe some considerations about this process.
@AngeloCG97  creo que podemos ampliar mucho mas la explicacion sobre este tema , alli te puse un ejemplo de un texto mas especifico.

2021-07-02 17:00 UTC, xavier506 commented on i18n/en/docusaurus-plugin-content-docs/current/guias/transacciones.md
> +To execute transaction on LACChain EOSIO it is necessary to include at least two actions for each transaction.
To execute `a` transaction

2021-07-02 17:02 UTC, xavier506 commented on i18n/en/docusaurus-plugin-content-docs/current/guias/transacciones.md
> +The smart contract action you would like to execute and writer::run action which includes the authorization of the writer node who will provide the necessary network resources to execute the transact
Each transaction must include at least the smart contract action you would like to execute and an additional `writer::run` action which includes the authorization of the writer node who will allow the transaction by providing the necessary network resources for the execute transaction to execute.

2021-07-04 22:25 UTC, xavier506 commented on docs/guias/transacciones.md
> +Cada transacción debe incluir al menos la acción de contrato inteligente que le gustaría ejecutar y una acción de **writer::run** adicional que incluye la autorización del nodo de escritura que permi
cambiar  nodo de escritura  por `nodo escritor`

2021-07-04 22:26 UTC, xavier506 requested changes
Creo que podemos ampliar este tema , que tal si tenemos algunos scripts en github que preparan transacciones como ejemplo ?

2021-07-05 15:10 UTC, AngeloCG97 commented
Añado un archivo al RP con los scripts?

2021-07-05 15:15 UTC, xavier506 commented
> Añado un archivo al RP con los scripts?

podriamos hacer un repo aparte con solo scripts de ejemplo , que te parece?

2021-07-06 00:01 UTC, xavier506 approved these changes
Esta bien por ahora , luego expandimos el contenido con los sample scripts

2021-07-06 00:01 UTC, merged