Incluir informacion sobre ambiente de desarrollo local
lacchain/eosio.lacchain.net pull request #123
Opened 2021-07-07 21:27 UTC by AngeloCG97

### Incluir informacion sobre ambiente de desarrollo local 

#114

## ¿Qué tiene este PR?
1. create new doc about local lacchain eosio

2021-07-07 21:51 UTC, xavier506 commented on docs/guias/ambiente-desarrollo.md
> +## 2. Ambiente de desarrollo local para LACChain EOSIO
@AngeloCG97  pongamos esto mas arriba ,  just después de la sección `1.2 Contract Development Toolkit`

2021-07-07 21:52 UTC, xavier506 commented on i18n/en/docusaurus-plugin-content-docs/current/guias/ambiente-desarrollo.md
> +## 2. Local development environment for LACChain EOSIO
@AngeloCG97  pongamos esto mas arriba ,  just después de la sección `1.2 Contract Development Toolkit`

2021-07-08 17:19 UTC, leisterfrancisco requested changes

2021-07-08 17:19 UTC, leisterfrancisco commented on docs/guias/ambiente-desarrollo.md
> +Para realizar pruebas mientras construye sus contratos puede generar un ambiente de desarrollo local sobre la red de LACChain EOSIO, esto le dara una serie de beneficios que puede consultar [aquí](..
add final point.

2021-07-08 17:19 UTC, leisterfrancisco commented on docs/herramientas/lacchain-eosio-local.md
> +## Empecemos
change Empecemos to Instrucciones para crear la imagen de LACChain EOSIO localmente

2021-07-08 17:19 UTC, leisterfrancisco commented on i18n/en/docusaurus-plugin-content-docs/current/guias/ambiente-desarrollo.md
> +To perform tests while building your contracts, you can generate a local development environment on the LACChain EOSIO network, this will give you a series of benefits that you can consult [here](../
Final point.

2021-07-08 17:19 UTC, leisterfrancisco commented on i18n/en/docusaurus-plugin-content-docs/current/herramientas/lacchain-eosio-local.md
> +## Let us begin
Change this title according spanish translation one

2021-07-09 16:33 UTC, xavier506 commented on docs/herramientas/lacchain-eosio-local.md
> +### Key de configuración
llave de configuracion?

2021-07-09 17:47 UTC, leisterfrancisco requested changes

2021-07-09 17:47 UTC, leisterfrancisco commented on .github/pull_request_template.md
> +## Issue de GH
?

2021-07-09 17:47 UTC, leisterfrancisco commented on .github/pull_request_template.md
> +### ¿Qué tiene este PR?
?

2021-07-09 17:47 UTC, leisterfrancisco commented on docs/guias/ambiente-desarrollo.md
> +Para realizar pruebas mientras construye sus contratos puede generar un ambiente de desarrollo local sobre la red de LACChain EOSIO, esto le dara una serie de beneficios que puede consultar [aquí](..
de desarrollo local sobre la red de LACChain EOSIO -> de desarrollo local de la red de LACChain EOSIO

dara -> dará

2021-07-09 17:47 UTC, leisterfrancisco commented on i18n/en/docusaurus-plugin-content-docs/current/herramientas/lacchain-eosio-local.md
> +### Contratos
Contratos?

2021-07-09 21:18 UTC, leisterfrancisco approved these changes

2021-07-09 22:03 UTC, xavier506 approved these changes
LGTM

2021-07-09 22:04 UTC, merged